### ISSUE TITLE
Invalid data format: Invalid passphrase - Can't send WEB from WEBCHAIN wallet to MINTME

### ISSUE THREAD

**Issue by Ymahern** [mintme-com/old-wallet#236]
``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

I'm trying to send WEB to MINTM and keep showing this screen, I already have MINTME app installed on my computer but I Can't see the WEBs that I have on WEBCHAIN Wallet. 
https://prnt.sc/sz6ksx
--

**Comment by danielwebimp** [comment]
@Ymahern  Hi, make sure your password is correct. That error occurs when the password is not OK. 
I encourage you to use instead our new Desktop wallet that you can download from here : https://github.com/mintme-com/wallet/releases , Take a backup of your wallet, then import it in the new software installed (Desktop wallet).

> ```
> JsonRpcError: Invalid data format: Invalid passphrase
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
>     at new JsonRpcError (file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
>     at file:///C:/Users/Admin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
> ```
> 
> ## I'm trying to send WEB to MINTM and keep showing this screen, I already have MINTME app installed on my computer but I Can't see the WEBs that I have on WEBCHAIN Wallet.
> https://prnt.sc/sz6ksx
