### ISSUE TITLE
Mnemonic error: Mnemonic generation error: invalid initial sentence length

### ISSUE THREAD

**Issue by Seifollahy** [mintme-com/old-wallet#251]
``` 
JsonRpcError: Mnemonic error: Mnemonic generation error: invalid initial sentence length
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:25935:30)
    at new JsonRpcError (file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:25964:116)
    at file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:26001:19
 ```

**Comment by Seifollahy** [comment]
JsonRpcError: Mnemonic error: Mnemonic generation error: invalid initial sentence length
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:25935:30)
    at new JsonRpcError (file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:25964:116)
    at file:///C:/Users/Mojtaba/AppData/Local/Programs/WEBCHA~1/resources/app.asar/app/index.js:26001:19
